### ISSUE TITLE
Cannot set nonlocal hook without a module handle

### ISSUE THREAD

**Issue by raminrahimzada** [alvanrahimli/BetterSizer#2]
Hi, nice project first of all
but It did not seem to work on me as intended

So debugging showed that inside KbHookHandler method
 SetWindowsHookEx  returns 0 (fails).
Immediately call to  GetLastError()  returns  [1428](https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--1300-1699-) which points the error message as issue title
Any idea how to fix ?

**Comment by alvanrahimli** [comment]
Thanks for kind words. 
Yes this is my mistake seems like I've pushed development version to main 😆 
To fix, please change `WH_MOUSE` to `WH_MOUSE_LL` at [this line](https://github.com/alvanrahimli/BetterSizer/blob/master/BetterSizer/BetterSizer.cpp#L85)

The reason is, there are 2 types of hooks in windows. Low level and global. We can hook global hooks to window's message loop (and intercept it) and low level hooks to window manager itself. WH_MOUSE is global hook, which means it needs to be hooked to target window's thread. And for this you need handle for target window thread. 

But low level hooks - in our case, WH_MOUSE_LL can be hooked to window manager and does not need any thread handle for this.

So, changing WH_MOUSE to WH_MOUSE_LL should fix your issue. I will also fix it in code you can also pull from main. 

Thanks again, for raising the issue 🤝

**Comment by raminrahimzada** [comment]
That solved my issue,
Thanks again for detailed explanation :)
